### ISSUE TITLE
Corrigir regressões

### ISSUE THREAD

**Issue by vitoria** [gabialverga/Guarabo#8]
As regressões dos métodos de girar não estão funcionando bem. Sugiro refazer os cálculos de medição ou verificar com novas linhas de tendência.
Issue aplicada ao código de python e c++.

**Comment by vitoria** [comment]
Fiz a mudança no código mas não consegui testar por que o robô não quis conectar.

**Comment by gabialverga** [comment]
Regressão de giro para a esquerda e direita corrigida!

**Comment by vitoria** [comment]
Obaa!!

**Comment by vitoria** [comment]
Issue completa, Gabi?
